[2025-02-07 17:36:51,455] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-07 17:37:20,578] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-07 17:37:21,439] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-07 17:39:43,907] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\middleware.py changed, reloading.
[2025-02-07 17:39:44,737] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-07 17:39:55,500] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\middleware.py changed, reloading.
[2025-02-07 17:39:56,281] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-07 17:42:19,182] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-07 17:42:19,984] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-07 17:42:30,707] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-07 17:42:31,637] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-07 17:42:37,207] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-07 17:42:38,189] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-07 17:47:07,879] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-07 17:48:03,467] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-07 17:48:04,425] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-07 17:48:19,439] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-07 17:48:20,170] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-07 17:48:28,756] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-07 17:48:29,569] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-07 17:52:06,833] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-07 17:52:08,591] [WARNING] [django.request] Not Found: /
[2025-02-07 17:53:39,860] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-07 17:53:40,725] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-07 17:53:52,699] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-07 17:53:53,423] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:24:50,403] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:24:53,096] [WARNING] [django.request] Bad Request: /signup/
[2025-02-10 13:25:30,575] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:25:31,361] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:25:38,804] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:25:40,230] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:25:45,659] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:25:46,474] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:26:16,921] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\models.py changed, reloading.
[2025-02-10 13:26:17,811] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:26:19,997] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\models.py changed, reloading.
[2025-02-10 13:26:20,840] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:26:29,108] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\admin.py changed, reloading.
[2025-02-10 13:26:29,916] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:27:02,893] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\admin.py changed, reloading.
[2025-02-10 13:27:03,713] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:28:29,833] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:28:30,740] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:28:33,981] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:28:34,985] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:28:37,314] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:28:38,193] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:28:40,871] [WARNING] [django.request] Not Found: /
[2025-02-10 13:28:40,968] [WARNING] [django.request] Not Found: /favicon.ico
[2025-02-10 13:28:54,245] [ERROR] [django.request] Internal Server Error: /admin/NoteApp/note/
Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 236, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'category'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: NoteApp_category.user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 345, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 321, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in __init__
    super().__init__(*items)
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 217, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\utils.py", line 310, in lookup_field
    value = getattr(obj, name)
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 254, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 217, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: NoteApp_category.user_id
[2025-02-10 13:28:58,211] [ERROR] [django.request] Internal Server Error: /admin/NoteApp/category/
Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: NoteApp_category.user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 2124, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: NoteApp_category.user_id
[2025-02-10 13:29:05,495] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:29:06,355] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:29:22,078] [ERROR] [django.request] Internal Server Error: /admin/NoteApp/category/
Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: NoteApp_category.user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 2124, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: NoteApp_category.user_id
[2025-02-10 13:29:50,352] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\admin.py changed, reloading.
[2025-02-10 13:29:51,209] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:29:57,679] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\models.py changed, reloading.
[2025-02-10 13:29:58,561] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:31:07,189] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:31:08,075] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:31:18,806] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\admin.py changed, reloading.
[2025-02-10 13:31:19,667] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:31:26,810] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\models.py changed, reloading.
[2025-02-10 13:31:27,788] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:31:29,936] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\models.py changed, reloading.
[2025-02-10 13:31:30,910] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:31:34,174] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\admin.py changed, reloading.
[2025-02-10 13:31:35,114] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:31:38,118] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\admin.py changed, reloading.
[2025-02-10 13:31:39,019] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:31:45,485] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:31:46,461] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:31:49,827] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:31:50,790] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:31:54,087] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:31:54,929] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:31:58,304] [WARNING] [django.request] Not Found: /
[2025-02-10 13:32:02,843] [ERROR] [django.request] Internal Server Error: /admin/NoteApp/customuser/
Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: NoteApp_customuser

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 1985, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 864, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\views\main.py", line 145, in __init__
    self.get_results(request)
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\views\main.py", line 312, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
           ^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 629, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 615, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: NoteApp_customuser
[2025-02-10 13:32:29,652] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:32:59,927] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\models.py changed, reloading.
[2025-02-10 13:33:00,730] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:33:07,828] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\admin.py changed, reloading.
[2025-02-10 13:33:08,652] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:33:11,615] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\admin.py changed, reloading.
[2025-02-10 13:33:12,397] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:33:15,406] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\admin.py changed, reloading.
[2025-02-10 13:33:16,194] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:33:22,541] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\admin.py changed, reloading.
[2025-02-10 13:33:23,433] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:33:25,540] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\admin.py changed, reloading.
[2025-02-10 13:33:26,344] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:33:34,789] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:33:35,685] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:33:40,111] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:33:40,915] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:33:49,543] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:33:50,282] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:33:53,479] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:33:54,319] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:33:57,208] [WARNING] [django.request] Not Found: /admin/NoteApp/customuser/
[2025-02-10 13:34:08,792] [ERROR] [django.request] Internal Server Error: /admin/NoteApp/signup/
Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: NoteApp_signup

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 1985, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 864, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\views\main.py", line 145, in __init__
    self.get_results(request)
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\views\main.py", line 312, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
           ^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 629, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 615, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: NoteApp_signup
[2025-02-10 13:34:34,856] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:35:01,778] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\admin.py changed, reloading.
[2025-02-10 13:35:02,612] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:35:10,634] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:36:49,255] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\models.py changed, reloading.
[2025-02-10 13:36:50,049] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:36:55,749] [WARNING] [django.request] Not Found: /
[2025-02-10 13:36:57,676] [ERROR] [django.request] Internal Server Error: /admin/NoteApp/signup/
Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: NoteApp_signup.user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 2124, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: NoteApp_signup.user_id
[2025-02-10 13:37:00,630] [ERROR] [django.request] Internal Server Error: /admin/NoteApp/signup/
Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: NoteApp_signup.user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 2124, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: NoteApp_signup.user_id
[2025-02-10 13:37:16,272] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:37:55,571] [ERROR] [django.request] Internal Server Error: /signup/
[2025-02-10 13:38:27,060] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:38:27,796] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:38:34,149] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:38:34,942] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:38:39,237] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 13:38:40,035] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 13:38:41,804] [WARNING] [django.request] Bad Request: /signup/
[2025-02-10 13:39:37,956] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\admin.py changed, reloading.
[2025-02-10 13:39:38,760] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 14:42:04,892] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 14:42:06,217] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:02:49,756] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:02:50,635] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:02:59,332] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:03:00,965] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:13:59,076] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:13:59,947] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:14:20,549] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:14:21,513] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:14:41,008] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:14:41,783] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:15:23,393] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:15:24,332] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:15:28,734] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:15:29,494] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:15:34,903] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:15:35,870] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:15:42,350] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:15:43,082] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:15:46,174] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:15:47,031] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:15:51,295] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:15:52,205] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:16:00,691] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:16:01,569] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:16:25,053] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:16:25,927] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:17:05,363] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:17:06,175] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:17:11,533] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:17:12,405] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:17:14,698] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:17:15,457] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:17:44,237] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:17:45,186] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-10 15:19:04,942] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-10 15:19:05,808] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-12 15:36:34,574] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-12 15:36:37,906] [WARNING] [django.request] Not Found: /
[2025-02-12 15:36:48,347] [WARNING] [django.request] Bad Request: /signup/
[2025-02-12 15:37:39,725] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-12 15:39:13,274] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-12 15:39:14,165] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-12 15:39:19,559] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-12 15:39:20,370] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-12 15:39:36,582] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-12 15:39:37,414] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-12 15:39:43,921] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-12 15:39:44,684] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-12 15:39:47,915] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-12 15:39:48,656] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-12 15:39:58,255] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-12 15:39:59,040] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-12 15:40:02,559] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-12 15:40:03,313] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-12 15:40:18,189] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-12 15:40:18,998] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:13:44,225] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:14:10,439] [WARNING] [django.request] Bad Request: /signup/
[2025-02-17 13:14:30,394] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:14:31,363] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:14:35,694] [WARNING] [django.request] Bad Request: /signup/
[2025-02-17 13:14:42,554] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:14:43,529] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:14:46,104] [WARNING] [django.request] Bad Request: /signup/
[2025-02-17 13:24:17,596] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:24:18,624] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:27:46,488] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:27:47,631] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:28:26,432] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:28:27,467] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:28:33,070] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:28:33,902] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:28:40,492] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:28:41,526] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:28:48,098] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:28:48,932] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:29:12,656] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:29:13,520] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:29:21,122] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:29:22,081] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:29:32,990] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:29:33,786] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:29:42,514] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:29:43,376] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:29:55,175] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:29:56,024] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:30:00,447] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:30:01,213] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:30:05,620] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:30:06,529] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:30:36,590] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:30:37,516] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:30:42,010] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:30:42,787] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:30:47,259] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:30:48,150] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:30:53,750] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:30:54,596] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:31:02,106] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:31:02,862] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:31:08,315] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:31:09,115] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:31:13,561] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:31:14,404] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 13:31:17,736] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 13:31:18,492] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:07:28,761] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:07:30,136] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:07:38,500] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:07:39,332] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:07:48,077] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:07:49,023] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:07:52,529] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:07:53,421] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:07:56,671] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:07:57,492] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:08:03,037] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:08:03,959] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:08:08,330] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:08:09,159] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:08:15,704] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:08:16,494] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:08:52,831] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:08:53,623] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:09:46,304] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:09:47,087] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:09:51,598] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:09:52,542] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:09:57,061] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:09:57,820] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:10:00,078] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:10:01,032] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:10:08,658] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:10:09,383] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:10:17,102] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:10:18,007] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:10:20,363] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:10:21,127] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:10:30,726] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:10:31,560] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:10:37,018] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:10:37,792] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:10:44,520] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:10:45,278] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:11:00,355] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:11:01,148] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:11:04,601] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:11:05,373] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:11:17,347] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:11:18,153] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:11:23,681] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:11:24,522] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:11:29,104] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:11:30,019] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:11:33,441] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:11:34,312] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:11:42,654] [WARNING] [django.request] Bad Request: /signup/
[2025-02-17 14:12:06,921] [WARNING] [django.request] Not Found: /
[2025-02-17 14:12:07,023] [WARNING] [django.request] Not Found: /favicon.ico
[2025-02-17 14:14:16,831] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:14:42,007] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:14:42,836] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:16:14,111] [WARNING] [django.request] Not Found: /api/filter/
[2025-02-17 14:16:52,536] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:17:03,712] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:17:04,492] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:18:02,660] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:18:03,937] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:18:05,721] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:18:14,118] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:18:15,072] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:18:21,634] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:18:22,422] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:18:27,866] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:18:28,749] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:18:31,564] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:18:56,243] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:18:57,269] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:19:05,129] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:19:12,463] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:21:30,270] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:21:36,232] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:21:41,586] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:22:40,656] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:22:41,511] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:23:01,000] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:23:01,794] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:23:04,199] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:23:05,074] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:23:09,572] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:24:10,693] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:24:25,733] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:24:26,551] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:24:37,374] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:24:38,281] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:24:44,082] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:24:52,676] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:24:53,477] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:25:09,074] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:25:09,925] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:25:27,165] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:25:28,005] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:25:32,554] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:25:33,282] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:25:41,929] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:26:10,030] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:26:10,854] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:26:14,328] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:26:15,181] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:26:18,713] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:26:19,505] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:26:24,991] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:26:25,753] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:26:30,145] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:26:30,890] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:26:33,139] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:26:34,012] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:26:37,019] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 14:30:49,832] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:30:50,794] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:30:55,370] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:30:56,220] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:31:00,806] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:31:01,858] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:32:52,531] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:32:53,349] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:34:39,846] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:34:40,610] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:34:44,117] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:34:44,881] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:34:47,113] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:34:47,897] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:34:55,487] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:34:56,259] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:34:59,739] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:35:00,509] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:35:02,886] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:35:03,805] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:35:12,545] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:35:13,313] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 14:35:23,030] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 14:35:23,854] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 15:51:33,712] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 15:51:54,241] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 15:51:55,641] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 15:51:58,359] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 15:51:59,548] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 15:52:04,178] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 15:52:05,772] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 15:52:16,072] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 15:52:17,097] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 15:53:13,196] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 15:53:14,034] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 15:53:55,841] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 15:53:56,841] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 15:58:29,357] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 15:58:30,252] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 15:58:47,858] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 15:58:48,857] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 15:58:56,694] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 15:58:57,763] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 15:59:00,350] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 15:59:01,201] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 15:59:39,606] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 15:59:40,564] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:11:18,532] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 16:11:48,731] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:11:51,276] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 16:14:00,965] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:14:01,771] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:14:03,042] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 16:14:24,558] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:14:25,434] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:14:27,793] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:14:28,594] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:14:33,167] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\urls.py changed, reloading.
[2025-02-17 16:14:33,922] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:14:37,268] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\urls.py changed, reloading.
[2025-02-17 16:14:38,113] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:14:45,735] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\urls.py changed, reloading.
[2025-02-17 16:14:46,587] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:14:53,337] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\urls.py changed, reloading.
[2025-02-17 16:14:54,229] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:14:57,627] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\urls.py changed, reloading.
[2025-02-17 16:14:58,543] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:15:09,484] [WARNING] [django.request] Not Found: /get_notes/
[2025-02-17 16:15:24,947] [ERROR] [django.request] Internal Server Error: /filter_category/
Traceback (most recent call last):
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wamiq\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
[2025-02-17 16:19:46,445] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:19:47,188] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:19:58,289] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:20:12,372] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\urls.py changed, reloading.
[2025-02-17 16:20:13,138] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:20:20,191] [WARNING] [django.request] Not Found: /filter_category/
[2025-02-17 16:20:25,079] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 16:31:51,223] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:31:52,055] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:31:55,710] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:31:56,447] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:32:03,854] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:32:07,050] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 16:32:15,102] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:32:15,915] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:32:18,203] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:32:18,966] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:32:21,234] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:32:21,991] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:32:24,370] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:32:25,203] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:32:28,687] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:32:29,551] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:32:32,893] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 16:32:37,556] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:32:38,327] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:32:43,827] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:32:44,594] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:32:48,127] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:32:49,076] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:50:59,359] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:51:00,253] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:51:03,705] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:51:04,591] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:51:11,258] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:51:12,057] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:51:14,314] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:51:15,206] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:51:17,737] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:51:18,552] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 16:51:28,338] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 16:51:29,179] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:05:09,641] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:33:24,279] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:33:25,056] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:33:35,998] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:33:36,872] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:33:40,206] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:33:41,229] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:33:45,581] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:33:46,468] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:33:50,805] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:33:51,697] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:33:55,069] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:33:55,904] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:33:59,250] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:34:00,280] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:34:02,647] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:34:03,426] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:34:09,446] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 17:34:43,637] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:34:44,511] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:34:47,821] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:34:48,647] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:34:54,165] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:34:54,920] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:34:58,913] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 17:35:10,383] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:35:11,312] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:35:13,607] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 17:37:19,581] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:37:20,556] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:37:27,231] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:37:28,220] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:37:42,249] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:37:43,132] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:37:44,359] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 17:41:37,969] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:41:38,791] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:41:52,827] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:41:53,766] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:42:13,259] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 17:43:01,917] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:43:02,856] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:43:10,494] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:43:11,263] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:43:57,559] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:43:58,306] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:44:03,680] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:44:04,440] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:44:17,390] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:44:18,117] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:44:22,440] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:44:23,178] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:44:26,562] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:44:27,444] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:44:32,943] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:44:33,720] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:44:40,387] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:44:41,169] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:44:43,548] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:44:44,280] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:44:46,721] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:44:47,614] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:44:49,976] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:44:50,714] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:45:00,405] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:45:01,183] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:45:06,633] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:45:07,378] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:45:24,691] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:45:25,574] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:45:33,126] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:45:34,027] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:45:40,603] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:45:41,445] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:46:00,842] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:46:01,583] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:46:06,039] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:46:06,970] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:46:10,311] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:46:11,118] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:46:19,508] [ERROR] [django.request] Internal Server Error: /filter/
[2025-02-17 17:46:32,049] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:46:32,848] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:50:42,435] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:50:43,277] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:50:45,891] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:50:46,688] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:50:52,194] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:50:53,013] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-02-17 17:50:56,368] [INFO] [django.utils.autoreload] F:\Note Project\Note\NoteApp\views.py changed, reloading.
[2025-02-17 17:50:57,301] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
